# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Raí Siqueira - Desenvolvedor Web
email: contato@raisiqueira.com
url: "http://raisiqueira.com" # the base hostname & protocol for your site
twitter_username: rai_siqueira
github_username:  raisiqueira

tagline:      Sou desenvolvedor Web desde 2008, com experiência em WordPress desde 2010. Atuo também como Analista de TI, tenho conhecimentos em Windows Server, Linux, Rede, Automação Comercial, SEO, SEM, E-Commerce, e um pouco de tudo que envolva um computador. Da uma olhadinha no meu LinkedIn :D
baseurl:      ""
paginate:     1


# About/contact
author:
  name:       Raí Siqueira
  url:        http://raisiqueira.com

# Gems
gems:
  - jekyll-paginate

# Build settings
markdown: kramdown
