# Site settings
title: "Raí Siqueira: Desenvolvedor Web"
description: "Portfolio for Raí Siqueira"
baseurl: ""
url: ""
twitter_username: rai_siqueira
github_username:  raisiqueira

# Build settings
permalink: pretty

# Sass settings
sass:
    sass_dir: _sass
    style: nested

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
      section: "blog"
      top_bar_color: "#3F51B5"
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      section: "portfolio"
      is_project: true
